config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root to: 'bookings#new', as: :home
    end

    unauthenticated :user do
      root to: 'devise/sessions#new'
    end
  end

  resources :users do
    member do
      get :set_password, as: :set_password
      post :save_password, as: :save_password
      get :set_card_info, as: :set_card_info
      post :save_card_info, as: :save_card_info
    end
  end

  resources :bookings do
    collection do
      post :confirm
      get :current
      post :cancel
      post :complete
    end
  end

  get 'calculate_fare', to: 'fare_estimate#calculate_fare', as: :calculate_fare

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :driver
  belongs_to :cab_type

  enum status: {
    pending: 0,
    started: 1,
    confirmed: 2,
    completed: 3,
    canceled: 4
  }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include FareEstimate
  include FindDriver
  include ErrorMessage

  before_action :authenticate_user!
  before_action :check_active_bookings, only: :new

  def new
    @cab_types = CabType.all
    @driver = Driver.new
  end

  def create
    source = params[:source_location]
    destination = params[:destination_location]
    cab_type = CabType.find(params[:cab_type])

    valid_location?(source, destination, params[:cab_type])

    if @error.nil?
      distance = calculate_distance(source.split(','), destination.split(',')).round(2)
      fare = calculate_fare_estimate(distance, cab_type).round(2)
      tax = calculate_tax(fare).round(2)
      total = (fare + tax)

      @driver = find_driver(source, cab_type)

      if @driver.nil?
        @error = 'Sorry. No cabs around.'
      else
        @booking = Booking.new(source: source, destination: destination,
                               source_name: params[:source], destination_name: params[:destination],
                               source_place_id: params[:source_place_id], destination_place_id: params[:destination_place_id],
                               distance: distance, price: total, user: current_user,
                               driver: @driver, status: 1, cab_type: cab_type)
        if @booking.save
          @driver.update(available: false)
          session[:current_booking] = @booking.id
        else
          @error = @driver.errors.full_messages.fist
        end
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def update
    @booking = Booking.find(session[:current_booking])
    if @booking.update!(booking_params)
      distance = calculate_distance(params[:booking][:source].split(','), params[:booking][:destination].split(',')).round(2)
      fare = calculate_fare_estimate(distance, @booking.cab_type).round(2)
      tax = calculate_tax(fare).round(2)
      total = (fare + tax)
      puts total
      @booking.update(distance: distance, price: total)
    else
      @error = @booking.errors.full_messages.first
    end

    respond_to do |format|
      format.js
    end
  end

  def confirm
    @booking = Booking.find(session[:current_booking])
    @booking.update(status: 2)
    redirect_to current_bookings_path
  end

  def current
    @booking = Booking.find(session[:current_booking])
    @driver = @booking.driver
    @cab_type = @booking.cab_type
  end

  def cancel
    @booking = Booking.find(session[:current_booking])
    @booking.update(status: 4)
    session[:current_booking] = nil
    respond_to do |format|
      format.js
    end
  end

  def complete
    @booking = Booking.find(session[:current_booking])
    @booking.update(status: 3)
    session[:current_booking] = nil
    respond_to do |format|
      format.js
    end
  end

  private

  def check_active_bookings
    redirect_to current_bookings_path if session[:current_booking]
  end

  def booking_params
    params.require(:booking).permit!
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_tag bookings_path, method: :post, remote: true do %>
  <div class="form-group">
    <%= text_field_tag :source, @source, class: 'form-control', placeholder: 'Source', autofocus: true %>
    <%= hidden_field_tag :source_location, nil %>
    <%= hidden_field_tag :source_place_id, nil %>
  </div>
  <div class="form-group">
    <%= text_field_tag :destination, nil, class: 'form-control', placeholder: 'Destination', autofocus: true %>
    <%= hidden_field_tag :destination_location, nil %>
    <%= hidden_field_tag :destination_place_id, nil %>
  </div>
  <div class="form-group">
    <h5><b>Ride Type</b></h5>
    <% @cab_types.each_with_index do |cab_type, index| %>
      <label class="radio-inline">
        <input type="radio" name="cab_type" value="<%= cab_type.id %>" <%= "checked" if index == 0 %>>
        <%= cab_type.name %>
      </label>
    <% end %>
  </div>
  <%= submit_tag 'Request Cab', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/bookings/cancel.js.erb
alertify.log('Your Trip has been cancelled');
window.location.href = "<%= root_path %>";

app/views/bookings/complete.js.erb
alertify.success('Your Trip has ended');
window.location.href = "<%= root_path %>";

app/views/bookings/create.js.erb
<% if @error.nil? %>
  alertify.success("Found a cab for you!");
  alertify.success("<%= @driver.name %> is on the way!");
  $('#driver_info').html("<%=j render('shared/driver_info', driver: @driver) %>");
  $('#confirm_booking_div').prop('disabled', false); 
<% else %>
  alertify.error("<%= @error %>");
<% end %>

app/views/bookings/current.html.erb
<div id="current" class="row">
  <div class="col-md-6 col-md-offset-1">
    <div class="well">
      <div class="row">
        <div class="col-md-6">
          <%= render 'shared/driver_info', driver: @driver %>
          <%= link_to 'Finish ride', complete_bookings_path, remote: true, method: :post, class: 'btn btn-success btn-block' %>
        </div>
        <div class="col-md-6">
          <br>
          <br>
          <%= form_for @booking, remote: true do |booking| %>
            <div class="form-group">
              <%= booking.text_field :source_name, id: 'source', class: 'form-control', placeholder: 'Source', readonly: true %> <br>
              <%= booking.hidden_field :source, id: 'source_location' %>
              <%= booking.hidden_field :source_place_id, id: 'source_place_id' %>
            </div>
            <div class="form-group">
              <%= booking.text_field :destination_name, id: 'destination', class: 'form-control', placeholder: 'Destination' %>
              <%= booking.hidden_field :destination, id: 'destination_location' %>
              <%= booking.hidden_field :destination_place_id, id: 'destination_place_id' %>
            </div>
            <%= booking.submit 'Update ride', class: 'btn btn-primary btn-block' %>
          <% end %>
          <%= link_to 'Cancel ride', cancel_bookings_path, remote: true, method: :post, class: 'btn btn-default btn-block' %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-12">
          <div id="map" style="height: 300px;"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="well">
      <h4 class="text-center">Total Fare</h4>
      <hr>
      <h2 id="total_fare" class="text-center"><%= @booking.price %> $</h2>
      <h4 id="cab_type" class="text-center"><%= @cab_type.name %></h4>
    </div>
    <div class="panel">
      <h3 class="text-center">Current Status</h3>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 left-fixed">
      <div class="content">
        <%= render 'bookings/form' %>
        <%= link_to 'Get Fare Estimate', calculate_fare_path, id: :get_fare_estimate, class: 'btn btn-default btn-block' %>
        <hr>
        <div id="driver_info">
          <%= render 'shared/driver_info', driver: @driver %>
        </div>
        <fieldset id="confirm_booking_div" disabled="true">
          <%= link_to 'Confirm', confirm_bookings_path, method: :post, id: 'confirm_booking', class: 'btn btn-success btn-block' %>
        </fieldset>
      </div>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 right-relative">
      <div id="map"></div>
    </div>
  </div>
</div>
<%= render 'shared/fare_estimate' %>
<% if flash[:message] %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:message] %>
  </div>
<% end %>

app/views/bookings/update.js.erb
<% if @error.nil? %>
  alertify.success('Trip has been updated');
<% else %>
  alertify.error("<%= @error %>");
<% end %>