config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root to: 'bookings#new', as: :home
    end

    unauthenticated :user do
      root to: 'devise/sessions#new'
    end
  end

  resources :users do
    member do
      get :set_password, as: :set_password
      post :save_password, as: :save_password
      get :set_card_info, as: :set_card_info
      post :save_card_info, as: :save_card_info
    end
  end

  resources :bookings do
    collection do
      post :confirm
      get :current
      post :cancel
      post :complete
    end
  end

  get 'calculate_fare', to: 'fare_estimate#calculate_fare', as: :calculate_fare

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :authentications
  has_many :bookings
  has_many :payments

  mount_uploader :avatar, AvatarUploader

  def self.find_for_oauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      user.update_attribute(:remote_avatar_url, auth.info.image.gsub('http://', 'https://'))
    else
      user = User.create(name: auth.info.name, email: auth.info.email,
                         password: Devise.friendly_token[0, 20], remote_avatar_url: auth.info.image.gsub('http://', 'https://'))
    end
    user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    authenticate_user(:facebook)
  end

  def google_oauth2
    authenticate_user(:google)
  end

  private

  def authenticate_user(_provider)
    auth = request.env['omniauth.auth']
    user = User.find_for_oauth(auth)
    authentication = Authentication.from_omniauth(auth, user)
    sign_in(user)
    if user.is_password_set?
      redirect_to set_card_info_user_path(user)
    else
      redirect_to set_password_user_path(user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def save_password
    if @user.update(password: params[:password], password_confirmation: params[:password_confirmation], phone: params[:phone])
      @user.is_password_set = true
      @user.save
      redirect_to set_card_info_user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.first
      redirect_to set_password_user_path(@user)
    end
  end

  def save_card_info
    @payment = Payment.new(holder_name: params[:holder_name], card_number: params[:card_number],
                           card_cvv: params[:card_cvv], card_expiry: params[:card_expiry], user: @user)

    if @payment.save
      @user.is_card_info_set = true
      if @user.save
        sign_in(@user)
        redirect_to root_path
      end
    else
      flash[:error] = @payment.errors.full_messages.first
      redirect_to set_card_info_user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    @user.profile_complete = true
    if @user.save
      sign_in @user, bypass: true
      redirect_to root_path
    else
      render 'set_password'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation,
                                 :avatar, :holder_name, :card_number, :card_cvv, :card_expiry)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/set_card_info.html.erb
<div id="card">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="well">
          <h3>Card Details</h3>
          <hr>
          <%= form_tag save_card_info_user_path(@user), method: :post do %>
            <div class="form-group">
              <%= text_field_tag :holder_name, nil, class: 'form-control', placeholder: 'Name on Card' %>
            </div>
            <div class="form-group">
              <%= text_field_tag :card_number, nil, class: 'form-control', placeholder: 'Card Number' %>
            </div>
            <div class="form-group">
              <%= text_field_tag :card_cvv, nil, class: 'form-control', placeholder: 'CVV' %>
            </div>
            <div class="form-group">
              <%= text_field_tag :card_expiry, nil, class: 'form-control', placeholder: 'MM/YY' %>
            </div>
            <div class="form-group">
              <%= submit_tag :complete, class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if flash[:error] %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/users/set_password.html.erb
<div class="page-content">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="well">
          <h3>Set Password &amp; Phone</h3>
          <hr>
          <%= form_tag save_password_user_path(@user) do %>
            <div class="form-group">
              <%= text_field_tag :phone, nil, class: 'form-control', placeholder: 'Phone Number' %>
            </div>
            <div class="form-group">
              <%= password_field_tag :password, nil, class: 'form-control', placeholder: 'password' %>
            </div>
            <div class="form-group">
              <%= password_field_tag :password_confirmation, nil, class: 'form-control', placeholder: 'Confirm Password' %>
            </div>
            <div class="form-group">
              <%= submit_tag :complete, class: 'btn btn-primary btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if flash[:error] %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= flash[:error] %>
  </div>
<% end %>